root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/dev"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
  exclude_file = ["*_test.go"]

[log]
  time = true
